import { Download, Moon, RotateCcw, Sun, Trash2 } from 'lucide-react'
import { useApp } from '../../app/AppContext'
import { Button } from '../../components/ui/Button'
import { defaultPreferences, persistence } from '../../persistence/db'

export function SettingsPage(){const {prefs,updatePrefs,runs,scenarios,reload}=useApp();const update=<K extends keyof typeof prefs>(key:K,value:typeof prefs[K])=>updatePrefs({...prefs,[key]:value});const exportData=()=>{const blob=new Blob([JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),runs,scenarios:scenarios.filter(s=>!s.pack)},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vimtype-data.json';a.click();URL.revokeObjectURL(a.href)};return <div className="page settings-page"><div className="page-title"><div><div className="eyebrow">PREFERENCES</div><h1>Make it yours.</h1><p>Settings are stored locally and apply to every drill.</p></div></div>
  <section className="settings-section"><div><h2>Appearance</h2><p>Set the visual tone of your editor.</p></div><div className="settings-panel"><div className="setting"><div><b>Theme</b><span>Choose a light or dark interface.</span></div><div className="segmented"><button className={prefs.theme==='dark'?'selected':''} onClick={()=>update('theme','dark')}><Moon size={15}/>Dark</button><button className={prefs.theme==='light'?'selected':''} onClick={()=>update('theme','light')}><Sun size={15}/>Light</button></div></div><div className="setting"><div><b>Editor font size</b><span>Adjust code readability.</span></div><div className="stepper"><button onClick={()=>update('fontSize',Math.max(12,prefs.fontSize-1))}>−</button><b>{prefs.fontSize}px</b><button onClick={()=>update('fontSize',Math.min(24,prefs.fontSize+1))}>+</button></div></div></div></section>
  <section className="settings-section"><div><h2>Editor</h2><p>Control editing defaults.</p></div><div className="settings-panel"><Toggle label="Relative line numbers" detail="Show distance from the cursor line." value={prefs.relativeLineNumbers} onChange={v=>update('relativeLineNumbers',v)}/><Toggle label="Completion sound" detail="Play a subtle tone when a run finishes." value={prefs.sound} onChange={v=>update('sound',v)}/><div className="setting"><div><b>Tab width</b><span>Used by imported and bundled scenarios.</span></div><select value={prefs.tabSize} onChange={e=>update('tabSize',Number(e.target.value))}><option value="2">2 spaces</option><option value="4">4 spaces</option></select></div></div></section>
  <section className="settings-section"><div><h2>Your data</h2><p>Runs never leave this browser.</p></div><div className="settings-panel data-actions"><div><div><b>Export local data</b><span>Download runs and imported scenarios as JSON.</span></div><Button variant="outline" onClick={exportData}><Download size={15}/>Export</Button></div><div><div><b>Reset preferences</b><span>Restore the default editor configuration.</span></div><Button variant="outline" onClick={()=>updatePrefs(defaultPreferences)}><RotateCcw size={15}/>Reset</Button></div><div><div><b>Delete all local data</b><span>Permanently erase history and imported content.</span></div><Button variant="danger" onClick={async()=>{if(confirm('Delete all Vimtype data from this browser?')){await persistence.clearAll();await reload()}}}><Trash2 size={15}/>Delete data</Button></div></div></section>
  </div>}
function Toggle({label,detail,value,onChange}:{label:string;detail:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="setting"><div><b>{label}</b><span>{detail}</span></div><button role="switch" aria-checked={value} onClick={()=>onChange(!value)} className={`toggle ${value?'on':''}`}><i/></button></div>}
